eticket/urls.py
from django.urls import include, path
from django.contrib import admin
from django.urls import path
from eticket.views import *

from django.contrib.auth import views as auth_views


urlpatterns = [

    path('', Home, name='home'),
    path('about/', About, name='about'),
    path('services/', Services, name='services'),
    path('register/', Register, name='register'),
    path('login/', Login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('booking/', Booking, name='booking'),
    path('success/', success, name='success'),
    path('book/', Book, name='book'),
    path('ngma/', ngma, name='ngma'),
    path('ticket/', Ticket, name="ticket"),

]

sih/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eticket.urls')),

]

eticket/models.py
from django.db import models
from django.contrib.auth.models import User


class Visitor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    dob = models.DateField()
    gender = models.CharField(max_length=30)
    phone = models.IntegerField()
    nationality = models.CharField(max_length=30)
    address = models.CharField(max_length=150)


def __str__(self):
    return self.user.user


class Booking_Detail(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    museumname = models.CharField(max_length=40)
    dov = models.DateField(max_length=20)
    time = models.TimeField(max_length=30)
    nob = models.IntegerField()


def __str__(self):
    return self.user.user


class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    booking_detail = models.ForeignKey(
        Booking_Detail, on_delete=models.CASCADE)
    qrcode = models.ImageField()


# class Show(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
#     museum_name = models.CharField(max_length=40)
#     time_slot = models.TimeField(max_length=30)
#     date = models.DateField(max_length=20)
#     price = models.IntegerField()

# def __str__(self):
#         return self.user.username

eticket/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login
from django.contrib import messages
from .models import *
import qrcode


def Home(request):
    return render(request, 'Home.html')


def About(request):
    return render(request, 'About.html')


def Services(request):
    return render(request, 'Services.html')


def Book(request):
    return render(request, 'Booking.html')


def success(request):
    return render(request, 'success.html')


def ngma(request):
    return render(request, 'NGMA.html')


def Login(request):
    error = ""
    if request.method == 'POST':
        u = request.POST['username']
        p = request.POST['password']
        user = authenticate(username=u, password=p)
        try:
            if user:
                login(request, user)
                return redirect('/')
            else:
                error = "Invalid username or password!!"
        except:
            error = "Invalid username or password!!"
    d = {'error': error}
    return render(request, 'Login.html', d)


def Register(request):
    error = ""
    if request.method == 'POST':
        us = request.POST['username']
        e = request.POST['email']
        pd = request.POST['password']
        ad = request.POST['address']
        nat = request.POST['nationality']
        do = request.POST['dob']
        c = request.POST['phone']
        g = request.POST['gender']
        try:
            user = User.objects.create_user(
                username=us, password=pd, email=e)
            Visitor.objects.create(
                user=user, nationality=nat, dob=do, phone=c, address=ad, gender=g)

            user = authenticate(username=us, password=pd)
            login(request, user)
            return redirect('/')
        except:
            error = "Unable to register!!"
    d = {'error': error}
    return render(request, 'Register.html', d)


def Booking(request):
    error = ""
    # if not request.user:
    #     return redirect('register')
    # ticket = Booking_Detail.objects.all()
    if request.method == 'POST':

        # us = request.POST['username']
        # e = request.POST['email']
        # pd = request.POST['password']
        mn = request.POST['museumname']
        dv = request.POST['dov']
        t = request.POST['time']
        nb = request.POST['nob']
        ua = User.objects.filter(username=request.user.username).first()
        try:

            Booking_Detail.objects.create(
                user=ua,
                museumname=mn, dov=dv, time=t, nob=nb)
            # ti = Booking_Detail.filter(id=request.booking_detail.id).first()
            # img = qrcode.make(ti)
            # qname = "code/"+str(ti)+".png"
            # qcode = qname.save(qname, "png")

            error = "no"
            return redirect('/success')

        except:
            error = "yes"
            d = {'error': error}
            return render(request, 'Booking.html', d)


def Ticket(request):
    return render(request, 'eticket.html')


# def Ticket(request):
#     # un = Booking_Detail.objects.get(username=request.user.username).first()
#     # no = Booking_Detail.objects.get(nob=request.Booking_Detail.nob)
#     # dv = Booking_Detail.objects.get(dov=request.Booking_Detail.dov)
#     # mn = Booking_Detail.objects.get(
#     #     museumname=request.booking_detail.museumname)
#     error = ""
#     bd = Booking_Detail.objects.filter(id= )
#     u = User.objects.get(id)
#     img = qrcode.make(bd)
#     qname = "code/"+str(bd)+".png"
#     qcode = qname.save(qname, "png")
#     try:

#         Ticket.objects.create(
#             user=u, booking_detail=bd,
#             qrcode=qcode)
#         et = Ticket.objects.get()
#         error = "no"
#         return redirect('/eticket')
#     except:
#         error = "yes"
#         d = {'error': error}
#         return render(request, 'Booking.html, d')

eticket/templates/About.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>About Us </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/About.css'%}">
    <link rel="stylesheet" href="{% static 'css/Footer.css'%}">
    <link rel="stylesheet" href="{% static 'css/Navbar.css'%}">
    <style>
        .button {
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

        .button1 {
            background-color: white;
            color: black;
            border: 2px solid #4CAF50;
        }

        .button1:hover {
            background-color: #4CAF50;
            color: white;
        }
    </style>

    <script src="https://kit.fontawesome.com/dbed6b6114.js" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="nav">
            <a href="" class="logo"><img src="{% static 'Images/logo.png' %}"></a>
            <div class="nav__link hide">
                <a href="../">home</a>
                {% if user.is_authenticated %}
                <a href="../services">services</a>
                <a class="button button1" href="../logout">Logout</button></a>
                {% else %}
                <a class="button button1" href="../register">Login</button></a>
                {% endif %}
            </div>
        </nav>
    </header>
    <section>
        <div class="image">
            <img src="{% static 'Images/museum.jpg' %}">

            <br>
        </div>
        <div class="content">
            <h2>About Us</h2>
            <span>
                <!-- line here -->
            </span>
            <p>The rich heritage of India, one of the world’s oldest civilizations, is an all-embracing confluence of
                religions, traditions and customs. The highlights of Indian heritage lie in the treasure of its art,
                architecture, classical dance, music, flora and fauna, and the innate secular philosophy of its people.
                A visit to the heritage sites is like a walk through history, changing lanes with every dynasty that
                ruled Indian soils. </p>
            <ul class="links">
                <li><a href="../">home</a></li>
                <div class="vertical-line"></div>
                {% if user.is_authenticated %}
                <li><a href="../services">Services</a></li>
                {% endif %}
                <div class="vertical-line"></div>
                <li><a href="#">contact</a></li>
            </ul>
            <ul class="icons">
                <li>
                    <a href="www.twitter.com"></a><i class="fa fa-twitter"></i>
                </li>
                <li>
                    <a href="www.facebook.com"></a><i class="fa fa-facebook"></i>
                </li>
                <li>
                    <a href="www.github.com"></a><i class="fa fa-github"></i>
                </li>
                <li>
                    <a href="www.pinterest.com"></a><i class="fa fa-pinterest"></i>
                </li>
            </ul>
        </div>
    </section><br><br>

</body>

</html>

eticket/templates/Booking.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}

    <title>NGMA Booking</title>
    <link rel="stylesheet" href="{% static 'css/Footer.css'%}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/Booking.css'%}" />

    <style>
        .button {
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
        }

        .button1 {
            background-color: white;
            color: black;
            border: 2px solid #4CAF50;
        }

        .button1:hover {
            background-color: #4CAF50;
            color: white;
        }
    </style>
</head>

<body>
    <header>
        <div class="nav">
            <a class="button button1" href="../services">Back</button></a>
        </div>
        </nav>
    </header>

    <div id="booking" class="section">
        <div class="section-center">
            <div class="container">

                <div class="row">
                    <div class="booking-form">
                        <div class="form-header1">
                            <h1>Book your Ticket</h1>
                        </div>
                        <form method="post" action="{% url 'booking' %}">
                            {% csrf_token %}

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <span class="form-label">Museum Name</span>
                                        <input class="form-control" type="text" placeholder="Enter the museum name"
                                            name="museumname" id="id_museumname">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <span class="form-label">Name</span>
                                        <input class="form-control" type="text" placeholder="Enter your name"
                                            name="username" id="id_username">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <span class="form-label">Price</span>
                                <input class="form-control" type="price" placeholder="" name="price" id="id_price">
                            </div>
                            <div class="form-group">
                                <span class="form-label">No. of tickets</span>
                                <input class="form-control" type="number" placeholder="Enter required no. of tickets"
                                    name="nob" id="id_nob">
                            </div>
                            <div class="row">
                                <div class="col-sm-5">
                                    <div class="form-group">
                                        <span class="form-label">Date of Visit</span>
                                        <input class="form-control" type="date" required name="dov" id="id_dov">
                                    </div>
                                </div>
                                <div class="col-sm-5">
                                    <div class="form-group">
                                        <span class="form-label">Time of Visit</span>
                                        <input class="form-control" type="time" required name="time" id="id_time">
                                    </div>
                                </div>
                                <!-- <div class="col-sm-7">
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <span class="form-label">Hour</span>
                                                <select class="form-control">
                                                    <option>1</option>
                                                    <option>2</option>
                                                    <option>3</option>
                                                    <option>4</option>
                                                    <option>5</option>
                                                    <option>6</option>
                                                    <option>7</option>
                                                    <option>8</option>
                                                    <option>9</option>
                                                    <option>10</option>
                                                    <option>11</option>
                                                    <option>12</option>
                                                </select>
                                                <span class="select-arrow"></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <span class="form-label">Min</span>
                                                <select class="form-control">
                                                    <option>05</option>
                                                    <option>10</option>
                                                    <option>15</option>
                                                    <option>20</option>
                                                    <option>25</option>
                                                    <option>30</option>
                                                    <option>35</option>
                                                    <option>40</option>
                                                    <option>45</option>
                                                    <option>50</option>
                                                    <option>55</option>
                                                </select>
                                                <span class="select-arrow"></span>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group">
                                                <span class="form-label">AM/PM</span>
                                                <select class="form-control">
                                                    <option>AM</option>
                                                    <option>PM</option>
                                                </select>
                                                <span class="select-arrow"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div> -->
                            </div>
                            <div class="form-btn">
                                <button type="submit" class="submit-btn">Book Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer>
        <div class="content">
            <div class="left box">
                <div class="upper">
                    <div class="topic">About us</div>
                    <p>Come and take a walk at one of the world's oldest civilizations, greatest architecture & rich
                        traditions
                        and customs of India.</p>
                </div>
                <div class="lower">
                    <div class="topic">Contact us</div>
                    <div class="phone">
                        <a href="#"><i class="fas fa-phone-volume"></i>+91 9000000000</a>
                    </div>
                    <div class="email">
                        <a href="#"><i class="fas fa-envelope"></i>abc@gmail.com</a>
                    </div>
                </div>
            </div>
            <div class="middle box">
                <div class="topic">Our Services</div>
                <div><a href="#">Ticket Booking</a></div>
                <div><a href="#">Exploring near-by Museums</a></div>
                <div><a href="#">QR-Based E-ticket</a></div>

            </div>
            <div class="right box">
                <div class="topic"></div>
                <form action="#">
                    <input type="text" placeholder="Find a museum/heritage site">
                    <input type="submit" name="" value="Send">
                    <div class="media-icons">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-youtube"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </form>
            </div>
        </div>
        <div class="bottom">
            <p>Copyright © 2022 <a href="#">Ministry of Culture</a> All rights reserved</p>
        </div>
    </footer>
</body>

</html>

eticket/templates/Home.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <!--<title> Responsive Footer | CodingLab</title>--->

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
  <link rel="stylesheet" href="{% static 'css/Home.css'%}">
  <link rel="stylesheet" href="{% static 'css/Navbar.css'%}">
  <link rel="stylesheet" href="{% static 'css/Footer.css'%}">



  <title>Museum&HeritageSite</title>

  <style>
    .button {
      border: none;
      color: white;
      padding: 16px 32px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 4px 2px;
      transition-duration: 0.4s;
      cursor: pointer;
    }

    .button1 {
      background-color: white;
      color: black;
      border: 2px solid #4CAF50;
    }

    .button1:hover {
      background-color: #4CAF50;
      color: white;
    }
  </style>
</head>

<body>
  <header>
    <nav class="nav">
      <a href="./" class="logo"><img src="{% static 'Images/logo.png' %}"></a>
      <div class="nav__link hide">
        <a href="./">home</a>
        <a href="./about">about</a>
        {% if user.is_authenticated %}
        <a href="./services">services</a>
        <a class="button button1" href="./logout">Logout</button></a>
        {% else %}
        <a class="button button1" href="./register">Login</button></a>
        {% endif %}
      </div>
    </nav>
    <marquee width="100%" direction="left" height="100px" style="color:rgb(0, 0, 0);">
      <img src="{% static 'Images/attention-hello.gif' %}" height="40px" width="40px">COVID-19 Appropriate behaviour -
      Wear Mask, Physical Distancing, Maintain Hand Hygiene - Ministry of Culture
    </marquee>
    <div class="box-form">
      <div class="left">
        <div class="overlay">
          <h1>Check Availability</h1>
          <a href="./login">Login to Book Tickets</a>
          <p>Don't have an account? <a href="./register">Create Your Account</a> it takes less than a minute</p>
        </div>
      </div>

      <div class="right">
        <h2>Search Availability for your Favourite Heritage Sites</h2>
        <div class="inputs">
          <input type="text" placeholder="Select State">
          <br>
          <input type="text" placeholder="Select Site">
          <br><br>
          <h4>Select your Date of Visit</h4>
          <input type="date" placeholder="Date of Visit">
        </div>

        <br><br>

        <button>Search</button>
      </div>

    </div>
  </header>

  <br> <br>
  <footer>
    <div class="content">
      <div class="left box">
        <div class="upper">
          <div class="topic">About us</div>
          <p>Come and take a walk at one of the world's oldest civilizations, greatest architecture & rich traditions
            and customs of India.</p>
        </div>
        <div class="lower">
          <div class="topic">Contact us</div>
          <div class="phone">
            <a href="#"><i class="fas fa-phone-volume"></i>+91 9000000000</a>
          </div>
          <div class="email">
            <a href="#"><i class="fas fa-envelope"></i>abc@gmail.com</a>
          </div>
        </div>
      </div>
      <div class="middle box">
        <div class="topic">Our Services</div>
        <div><a href="#">Ticket Booking</a></div>
        <div><a href="#">Exploring near-by Museums</a></div>
        <div><a href="#">QR-Based E-ticket</a></div>

      </div>
      <div class="right box">
        <div class="topic"></div>
        <form action="#">
          <input type="text" placeholder="Send Feedback">
          <input type="submit" name="" value="Send">
          <div class="media-icons">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-youtube"></i></a>
            <a href="#"><i class="fab fa-linkedin-in"></i></a>
          </div>
        </form>
      </div>
    </div>
    <div class="bottom">
      <p>Copyright © 2022 <a href="#">Ministry of Culture</a> All rights reserved</p>
    </div>
  </footer>


</body>

</html>

eticket/templates/Login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Login.css'%}">
    <link rel="stylesheet" href="{% static 'css/Navbar.css'%}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,500;1,100&display=swap"
        rel="stylesheet">

</head>

<body>
    <header>
        <nav class="nav">
            <a href="../" class="logo"><img src="{% static 'Images/logo.png' %}"></a>
            <div class="nav__link hide">
                <a href="../">home</a>
                <a href="../about">about</a>
            </div>
        </nav>
    </header>
    <div class="wrapper">
        <form class="login">
            <p class="title">Log in</p>
            <input type="text" placeholder="Username" autofocus />
            <i class="fa fa-user"></i>
            <input type="password" placeholder="Password" />
            <i class="fa fa-key"></i>
            <a href="#">Forgot your password?</a>
            <button type="submit">
                <i class="spinner"></i>
                <span class="state">Log in</span>
            </button>
        </form>
        </p>
    </div>
    <script src="{% static 'js/Login.js'%}"></script>
</body>

</html>

eticket/templates/Register.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/Register.css'%}">
    <link rel="stylesheet" href="{% static 'css/Navbar.css'%}">
</head>

<body>
    <header>
        <nav class="nav">
            <a href="../" class="logo"><img src="{% static 'Images/logo.png' %}"></a>
            <div class="nav__link hide">
                <a href="../">home</a>
                <a href="../about">about</a>
            </div>
        </nav>
    </header>
    <div class="cotn_principal">
        <div class="cont_centrar">

            <div class="cont_login">
                <br>
                {% if error %}
                <h4 style="font-size: 20px; color: blanchedalmond; font-style: bold;">
                    {{error|escape}}
                </h4>
                {% endif %}
                <div class="cont_info_log_sign_up">
                    <div class="col_md_login">

                        <div class="cont_ba_opcitiy">

                            <h2>LOGIN</h2>
                            <p>WELCOME BACK!!</p>
                            <button class="btn_login" onclick="cambiar_login()">LOGIN</button>
                        </div>
                    </div>
                    <div class="col_md_sign_up">
                        <div class="cont_ba_opcitiy">
                            <h2>REGISTER</h2>


                            <p>Don't have an account? Sign up here</p>

                            <button class="btn_sign_up" onclick="cambiar_sign_up()">SIGN UP</button>
                        </div>
                    </div>
                </div>


                <div class="cont_back_info">
                    <div class="cont_img_back_grey">
                        <img src="{% static 'Images/registerbg.jpg' %}" alt="" />
                    </div>

                </div>
                <div class="cont_forms">
                    <div class="cont_img_back_">
                        <img src="{% static 'Images/registerbg.jpg' %}" alt="" />
                    </div>
                    <form method="post" action="{% url 'login' %}" class="cont_form_login">
                        {% csrf_token %}
                        <a href="#" onclick="ocultar_login_sign_up()"><i class="material-icons">&#xE5C4;</i></a>
                        <h2>LOGIN</h2>
                        <input type="text" placeholder="Username" name="username" id="id_username" />
                        <input type="password" placeholder="Password" name="password" id="id_password" />
                        <button type="submit" class="btn_login" onclick="cambiar_login()">LOGIN</button>

                    </form>

                    <form method="post" action="{% url 'register' %}" class="cont_form_sign_up">
                        {% csrf_token %}
                        <a href="#" onclick="ocultar_login_sign_up()"><i class="material-icons">&#xE5C4;</i></a>
                        <h2>SIGN UP</h2>
                        <input type="text" placeholder="Email" name="email" id="id_email" />
                        <input type="text" placeholder="Username" name="username" id="id_username" />
                        <input type="number" placeholder="Phone Number" name="phone" id="id_phone" />
                        <input type="text" placeholder="Address" name="address" id="id_address" />
                        <input type="text" placeholder="Nationality" name="nationality" id="id_nationality" />
                        <input type="date" placeholder="DoB" name="dob" id="id_dob" /><br>
                        <select name="gender" id="gender-select" id="id_gender">
                            <option value="">--Gender--</option>
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                            <option value="other">Other</option>
                            <option value="pns">Prefer not to say</option>
                        </select>
                        <input type="password" placeholder="Password" name="password" id="id_password" />
                        <button class="btn_sign_up" onclick="cambiar_sign_up()" type="submit">SIGN UP</button>

                    </form>

                </div>

            </div>
        </div>
    </div>
    <script src="{% static 'js/Register.js'%}"></script>
    <div class="footer">
        <p>Footer</p>
        Copyright ©-All rights are reserved

    </div>
</body>

</html>

eticket/templates/success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
</head>

<body>
    <h1>SUCCESS!!</h1>
</body>

</html>